/*
 * SingleThread - Task-Centric Wayland Compositor
 * server.h - Core server state and lifecycle
 */
#ifndef STW_SERVER_H
#define STW_SERVER_H

#include <stdbool.h>
#include <wayland-server-core.h>
#include <wlr/backend.h>
#include <wlr/render/allocator.h>
#include <wlr/render/wlr_renderer.h>
#include <wlr/types/wlr_compositor.h>
#include <wlr/types/wlr_cursor.h>
#include <wlr/types/wlr_data_device.h>
#include <wlr/types/wlr_input_device.h>
#include <wlr/types/wlr_keyboard.h>
#include <wlr/types/wlr_layer_shell_v1.h>
#include <wlr/types/wlr_output.h>
#include <wlr/types/wlr_output_layout.h>
#include <wlr/types/wlr_pointer.h>
#include <wlr/types/wlr_scene.h>
#include <wlr/types/wlr_seat.h>
#include <wlr/types/wlr_subcompositor.h>
#include <wlr/types/wlr_xcursor_manager.h>
#include <wlr/types/wlr_xdg_shell.h>
#include <wlr/types/wlr_xdg_decoration_v1.h>

/* Build config header generated by meson */
#include "config.h"

/* Forward declarations */
struct stw_view;
struct stw_task;
struct stw_output;
struct stw_keyboard;
struct stw_rule;

/* ─── Cursor modes ─────────────────────────────────────────────── */
enum stw_cursor_mode {
	STW_CURSOR_PASSTHROUGH,
	STW_CURSOR_MOVE,
	STW_CURSOR_RESIZE,
};

/* ─── Core server state ────────────────────────────────────────── */
struct stw_server {
	struct wl_display *wl_display;
	struct wl_event_loop *wl_event_loop;

	/* Backend and rendering */
	struct wlr_backend *backend;
	struct wlr_renderer *renderer;
	struct wlr_allocator *allocator;
	struct wlr_scene *scene;
	struct wlr_scene_output_layout *scene_layout;

	/* Wayland globals */
	struct wlr_compositor *compositor;
	struct wlr_subcompositor *subcompositor;
	struct wlr_data_device_manager *data_device_mgr;

	/* Shell protocols */
	struct wlr_xdg_shell *xdg_shell;
	struct wlr_layer_shell_v1 *layer_shell;
	struct wlr_xdg_decoration_manager_v1 *xdg_decoration_mgr;

	/* Outputs */
	struct wlr_output_layout *output_layout;
	struct wl_list outputs; /* stw_output.link */
	struct wl_listener new_output;

	/* Input */
	struct wlr_seat *seat;
	struct wlr_cursor *cursor;
	struct wlr_xcursor_manager *cursor_mgr;
	struct wl_list keyboards; /* stw_keyboard.link */
	struct wl_listener new_input;
	struct wl_listener cursor_motion;
	struct wl_listener cursor_motion_absolute;
	struct wl_listener cursor_button;
	struct wl_listener cursor_axis;
	struct wl_listener cursor_frame;
	struct wl_listener request_set_cursor;
	struct wl_listener request_set_selection;

	/* Interactive move/resize state */
	enum stw_cursor_mode cursor_mode;
	struct stw_view *grabbed_view;
	double grab_x, grab_y;
	struct wlr_box grab_geobox;
	uint32_t resize_edges;

	/* XDG shell listener */
	struct wl_listener new_xdg_toplevel;
	struct wl_listener new_xdg_popup;
	struct wl_listener new_layer_surface;
	struct wl_listener xdg_decoration;

	/* XWayland */
#if STW_HAS_XWAYLAND
	struct wlr_xwayland *xwayland;
	struct wl_listener xwayland_ready;
	struct wl_listener new_xwayland_surface;
#endif

	/* ─── Task system ──────────────────────────────────────────── */
	struct wl_list tasks;       /* stw_task.link */
	struct stw_task *active_task;
	uint32_t next_task_id;

	/* Scene tree layers (bottom to top) */
	struct wlr_scene_tree *scene_background;
	struct wlr_scene_tree *scene_tiled;
	struct wlr_scene_tree *scene_floating;
	struct wlr_scene_tree *scene_fullscreen;
	struct wlr_scene_tree *scene_global;
	struct wlr_scene_tree *scene_overlay;

	/* ─── Views (all managed windows) ──────────────────────────── */
	struct wl_list views; /* stw_view.link (all views) */

	/* ─── Rules engine ─────────────────────────────────────────── */
	struct wl_list rules; /* stw_rule.link */

	/* ─── IPC ──────────────────────────────────────────────────── */
	int ipc_socket_fd;
	struct wl_event_source *ipc_event_source;
	struct wl_list ipc_clients; /* stw_ipc_client.link */

	/* ─── Configuration ────────────────────────────────────────── */
	struct stw_config *config;
	char *config_path;

	/* ─── Session persistence ──────────────────────────────────── */
	char *session_path;

	/* Socket name for clients */
	const char *socket;

	/* Running flag */
	bool running;
};

/* Server lifecycle */
bool stw_server_init(struct stw_server *server);
void stw_server_run(struct stw_server *server);
void stw_server_finish(struct stw_server *server);

/* Focus management */
void stw_server_focus_view(struct stw_server *server, struct stw_view *view);
struct stw_view *stw_server_view_at(struct stw_server *server,
	double lx, double ly, struct wlr_surface **surface,
	double *sx, double *sy);

#endif /* STW_SERVER_H */
